name: Deploy Résumé Site

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-fonts-extra \
            texlive-latex-extra \
            texlive-fonts-recommended

      - name: Compile Résumé PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume/resume.tex
          compiler: latexmk

      - name: Prepare Pages files
        run: |
          mkdir -p public/resume
          cp resume/resume.pdf public/resume/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
