name: Build Résumé PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install extra LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-fonts-extra texlive-latex-extra texlive-fonts-recommended
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume/resume.tex
          compiler: latexmk
      - name: Upload LaTeX log
        uses: actions/upload-artifact@v3
        with:
          name: latex-log
          path: resume/resume.log
      - name: Deploy PDF to Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/resume.pdf
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
      - name: List files
        run: ls -R
